"""Add Phase 3.2-3.4 models: Staff, Schedule, LabTest, LabResult, NotificationTemplate, ClientCommunicationPreference, Reminder

Revision ID: 55099e3cc37a
Revises: ff82e83bae8e
Create Date: 2025-11-02 22:55:10.407743

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55099e3cc37a'
down_revision = 'ff82e83bae8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('patient_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('client_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('appointment_type_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('assigned_staff_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('room', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('check_in_time', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('actual_start_time', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('actual_end_time', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('cancelled_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('cancelled_by_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('cancellation_reason', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('reminder_sent', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('reminder_sent_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('created_by_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=200),
               existing_nullable=False)
        batch_op.create_index(batch_op.f('ix_appointment_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_appointment_end_time'), ['end_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_appointment_start_time'), ['start_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_appointment_status'), ['status'], unique=False)
        batch_op.create_foreign_key(None, 'patient', ['patient_id'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['created_by_id'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['assigned_staff_id'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['cancelled_by_id'], ['id'])
        batch_op.create_foreign_key(None, 'appointment_type', ['appointment_type_id'], ['id'])
        batch_op.create_foreign_key(None, 'client', ['client_id'], ['id'])

    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tax_rate', sa.Numeric(precision=5, scale=2), nullable=False))
        batch_op.alter_column('patient_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('invoice_date',
               existing_type=sa.DATETIME(),
               type_=sa.Date(),
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.drop_column('internal_notes')

    with op.batch_alter_table('invoice_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_price', sa.Numeric(precision=10, scale=2), nullable=False))
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.drop_column('line_total')
        batch_op.drop_column('tax_amount')
        batch_op.drop_column('tax_rate')

    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('card_type')
        batch_op.drop_column('status')
        batch_op.drop_column('card_last_four')

    with op.batch_alter_table('service', schema=None) as batch_op:
        batch_op.add_column(sa.Column('service_type', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False))
        batch_op.alter_column('category',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.drop_column('code')
        batch_op.drop_column('default_price')
        batch_op.drop_column('tax_rate')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tax_rate', sa.NUMERIC(precision=5, scale=2), nullable=True))
        batch_op.add_column(sa.Column('default_price', sa.NUMERIC(precision=10, scale=2), nullable=False))
        batch_op.add_column(sa.Column('code', sa.VARCHAR(length=50), nullable=False))
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('category',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.drop_column('unit_price')
        batch_op.drop_column('service_type')

    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('card_last_four', sa.VARCHAR(length=4), nullable=True))
        batch_op.add_column(sa.Column('status', sa.VARCHAR(length=20), nullable=False))
        batch_op.add_column(sa.Column('card_type', sa.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DATETIME(), nullable=False))
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)

    with op.batch_alter_table('invoice_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tax_rate', sa.NUMERIC(precision=5, scale=2), nullable=True))
        batch_op.add_column(sa.Column('tax_amount', sa.NUMERIC(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('line_total', sa.NUMERIC(precision=10, scale=2), nullable=False))
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.drop_column('total_price')

    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.add_column(sa.Column('internal_notes', sa.TEXT(), nullable=True))
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('invoice_date',
               existing_type=sa.Date(),
               type_=sa.DATETIME(),
               existing_nullable=False)
        batch_op.alter_column('patient_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('tax_rate')

    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_appointment_status'))
        batch_op.drop_index(batch_op.f('ix_appointment_start_time'))
        batch_op.drop_index(batch_op.f('ix_appointment_end_time'))
        batch_op.drop_index(batch_op.f('ix_appointment_client_id'))
        batch_op.alter_column('title',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_by_id')
        batch_op.drop_column('created_at')
        batch_op.drop_column('reminder_sent_at')
        batch_op.drop_column('reminder_sent')
        batch_op.drop_column('notes')
        batch_op.drop_column('cancellation_reason')
        batch_op.drop_column('cancelled_by_id')
        batch_op.drop_column('cancelled_at')
        batch_op.drop_column('actual_end_time')
        batch_op.drop_column('actual_start_time')
        batch_op.drop_column('check_in_time')
        batch_op.drop_column('room')
        batch_op.drop_column('assigned_staff_id')
        batch_op.drop_column('status')
        batch_op.drop_column('appointment_type_id')
        batch_op.drop_column('client_id')
        batch_op.drop_column('patient_id')

    # ### end Alembic commands ###
