"""Add Phase 3.5 models: ClientPortalUser and AppointmentRequest

Revision ID: 80e9d186e84d
Revises: 55099e3cc37a
Create Date: 2025-11-02 22:59:38.256692

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80e9d186e84d'
down_revision = '55099e3cc37a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client_portal_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('verification_token', sa.String(length=100), nullable=True),
    sa.Column('reset_token', sa.String(length=100), nullable=True),
    sa.Column('reset_token_expiry', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=True),
    sa.Column('account_locked_until', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('appointment_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('appointment_type_id', sa.Integer(), nullable=True),
    sa.Column('requested_date', sa.Date(), nullable=False),
    sa.Column('requested_time', sa.String(length=20), nullable=True),
    sa.Column('alternate_date_1', sa.Date(), nullable=True),
    sa.Column('alternate_date_2', sa.Date(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('is_urgent', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('reviewed_by_id', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('staff_notes', sa.Text(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('appointment_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointment.id'], ),
    sa.ForeignKeyConstraint(['appointment_type_id'], ['appointment_type.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('patient_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('client_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('appointment_type_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('assigned_staff_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('room', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('check_in_time', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('actual_start_time', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('actual_end_time', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('cancelled_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('cancelled_by_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('cancellation_reason', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('reminder_sent', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('reminder_sent_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('created_by_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=200),
               existing_nullable=False)
        batch_op.create_index(batch_op.f('ix_appointment_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_appointment_end_time'), ['end_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_appointment_start_time'), ['start_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_appointment_status'), ['status'], unique=False)
        batch_op.create_foreign_key('fk_appointment_client_id', 'client', ['client_id'], ['id'])
        batch_op.create_foreign_key('fk_appointment_created_by_id', 'user', ['created_by_id'], ['id'])
        batch_op.create_foreign_key('fk_appointment_appointment_type_id', 'appointment_type', ['appointment_type_id'], ['id'])
        batch_op.create_foreign_key('fk_appointment_patient_id', 'patient', ['patient_id'], ['id'])
        batch_op.create_foreign_key('fk_appointment_cancelled_by_id', 'user', ['cancelled_by_id'], ['id'])
        batch_op.create_foreign_key('fk_appointment_assigned_staff_id', 'user', ['assigned_staff_id'], ['id'])

    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tax_rate', sa.Numeric(precision=5, scale=2), nullable=False))
        batch_op.alter_column('patient_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('invoice_date',
               existing_type=sa.DATETIME(),
               type_=sa.Date(),
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.drop_column('internal_notes')

    with op.batch_alter_table('invoice_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_price', sa.Numeric(precision=10, scale=2), nullable=False))
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.drop_column('line_total')
        batch_op.drop_column('tax_rate')
        batch_op.drop_column('tax_amount')

    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.drop_column('card_last_four')
        batch_op.drop_column('card_type')
        batch_op.drop_column('status')
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('service', schema=None) as batch_op:
        batch_op.add_column(sa.Column('service_type', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False))
        batch_op.alter_column('category',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.drop_column('default_price')
        batch_op.drop_column('tax_rate')
        batch_op.drop_column('code')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service', schema=None) as batch_op:
        batch_op.add_column(sa.Column('code', sa.VARCHAR(length=50), nullable=False))
        batch_op.add_column(sa.Column('tax_rate', sa.NUMERIC(precision=5, scale=2), nullable=True))
        batch_op.add_column(sa.Column('default_price', sa.NUMERIC(precision=10, scale=2), nullable=False))
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('category',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.drop_column('unit_price')
        batch_op.drop_column('service_type')

    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DATETIME(), nullable=False))
        batch_op.add_column(sa.Column('status', sa.VARCHAR(length=20), nullable=False))
        batch_op.add_column(sa.Column('card_type', sa.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('card_last_four', sa.VARCHAR(length=4), nullable=True))
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)

    with op.batch_alter_table('invoice_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tax_amount', sa.NUMERIC(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('tax_rate', sa.NUMERIC(precision=5, scale=2), nullable=True))
        batch_op.add_column(sa.Column('line_total', sa.NUMERIC(precision=10, scale=2), nullable=False))
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.drop_column('total_price')

    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.add_column(sa.Column('internal_notes', sa.TEXT(), nullable=True))
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('invoice_date',
               existing_type=sa.Date(),
               type_=sa.DATETIME(),
               existing_nullable=False)
        batch_op.alter_column('patient_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('tax_rate')

    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.drop_constraint('fk_appointment_assigned_staff_id', type_='foreignkey')
        batch_op.drop_constraint('fk_appointment_cancelled_by_id', type_='foreignkey')
        batch_op.drop_constraint('fk_appointment_patient_id', type_='foreignkey')
        batch_op.drop_constraint('fk_appointment_appointment_type_id', type_='foreignkey')
        batch_op.drop_constraint('fk_appointment_created_by_id', type_='foreignkey')
        batch_op.drop_constraint('fk_appointment_client_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_appointment_status'))
        batch_op.drop_index(batch_op.f('ix_appointment_start_time'))
        batch_op.drop_index(batch_op.f('ix_appointment_end_time'))
        batch_op.drop_index(batch_op.f('ix_appointment_client_id'))
        batch_op.alter_column('title',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_by_id')
        batch_op.drop_column('created_at')
        batch_op.drop_column('reminder_sent_at')
        batch_op.drop_column('reminder_sent')
        batch_op.drop_column('notes')
        batch_op.drop_column('cancellation_reason')
        batch_op.drop_column('cancelled_by_id')
        batch_op.drop_column('cancelled_at')
        batch_op.drop_column('actual_end_time')
        batch_op.drop_column('actual_start_time')
        batch_op.drop_column('check_in_time')
        batch_op.drop_column('room')
        batch_op.drop_column('assigned_staff_id')
        batch_op.drop_column('status')
        batch_op.drop_column('appointment_type_id')
        batch_op.drop_column('client_id')
        batch_op.drop_column('patient_id')

    op.drop_table('appointment_request')
    op.drop_table('client_portal_user')
    # ### end Alembic commands ###
