"""Enhance Pet model to comprehensive Patient model with cat-specific fields

Revision ID: ef07ccabb369
Revises: 332b5c62c0d3
Create Date: 2025-10-26 11:17:11.515559

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef07ccabb369'
down_revision = '332b5c62c0d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pet')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pet',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('breed', sa.VARCHAR(length=100), nullable=True),
    sa.Column('owner', sa.VARCHAR(length=100), nullable=True),
    sa.Column('species', sa.VARCHAR(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
