"""enhance appointment model with type, status, staff, and workflow fields

Revision ID: ff82e83bae8e
Revises: ef07ccabb369
Create Date: 2025-10-26 19:07:19.615512

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff82e83bae8e'
down_revision = 'ef07ccabb369'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('patient_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('client_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('appointment_type_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('assigned_staff_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('room', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('check_in_time', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('actual_start_time', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('actual_end_time', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('cancelled_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('cancelled_by_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('cancellation_reason', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('reminder_sent', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('reminder_sent_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('created_by_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=200),
               existing_nullable=False)
        batch_op.create_index(batch_op.f('ix_appointment_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_appointment_end_time'), ['end_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_appointment_start_time'), ['start_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_appointment_status'), ['status'], unique=False)
        batch_op.create_foreign_key('fk_appointment_client_id', 'client', ['client_id'], ['id'])
        batch_op.create_foreign_key('fk_appointment_cancelled_by_id', 'user', ['cancelled_by_id'], ['id'])
        batch_op.create_foreign_key('fk_appointment_patient_id', 'patient', ['patient_id'], ['id'])
        batch_op.create_foreign_key('fk_appointment_created_by_id', 'user', ['created_by_id'], ['id'])
        batch_op.create_foreign_key('fk_appointment_assigned_staff_id', 'user', ['assigned_staff_id'], ['id'])
        batch_op.create_foreign_key('fk_appointment_appointment_type_id', 'appointment_type', ['appointment_type_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.drop_constraint('fk_appointment_appointment_type_id', type_='foreignkey')
        batch_op.drop_constraint('fk_appointment_assigned_staff_id', type_='foreignkey')
        batch_op.drop_constraint('fk_appointment_created_by_id', type_='foreignkey')
        batch_op.drop_constraint('fk_appointment_patient_id', type_='foreignkey')
        batch_op.drop_constraint('fk_appointment_cancelled_by_id', type_='foreignkey')
        batch_op.drop_constraint('fk_appointment_client_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_appointment_status'))
        batch_op.drop_index(batch_op.f('ix_appointment_start_time'))
        batch_op.drop_index(batch_op.f('ix_appointment_end_time'))
        batch_op.drop_index(batch_op.f('ix_appointment_client_id'))
        batch_op.alter_column('title',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_by_id')
        batch_op.drop_column('created_at')
        batch_op.drop_column('reminder_sent_at')
        batch_op.drop_column('reminder_sent')
        batch_op.drop_column('notes')
        batch_op.drop_column('cancellation_reason')
        batch_op.drop_column('cancelled_by_id')
        batch_op.drop_column('cancelled_at')
        batch_op.drop_column('actual_end_time')
        batch_op.drop_column('actual_start_time')
        batch_op.drop_column('check_in_time')
        batch_op.drop_column('room')
        batch_op.drop_column('assigned_staff_id')
        batch_op.drop_column('status')
        batch_op.drop_column('appointment_type_id')
        batch_op.drop_column('client_id')
        batch_op.drop_column('patient_id')

    # ### end Alembic commands ###
